# .github/workflows/ci.yml
name: CI & Static Deploy

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Type check (non-blocking)
        run: |
          if [ -f tsconfig.json ]; then
            npx tsc --noEmit || true
          fi

      - name: Build (Next static export)
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          GITHUB_PAGES: "true"
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -e
          npm run build
          test -d out || (echo "Expected ./out directory not found — check next.config.js { output: 'export' }" && exit 1)

      - name: Zip static site
        run: |
          cd out && zip -r ../site.zip . && cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: site-zip
          path: site.zip

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
